import { mkdir, writeFile, readFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import type { AgentContext } from "../agents/context.js";
import { slugify, type MediaAsset, type Project, type Shot, type ShotStatus } from "../model/index.js";
import { MediaUnavailableError } from "./provider.js";

const EXT: Record<string, string> = { "image/png": "png", "image/jpeg": "jpg", "image/svg+xml": "svg", "image/webp": "webp", "video/mp4": "mp4", "audio/wav": "wav", "audio/mpeg": "mp3" };

async function writeAsset(mediaDir: string, relPath: string, bytes: Uint8Array): Promise<void> {
  const full = join(mediaDir, relPath);
  await mkdir(dirname(full), { recursive: true });
  await writeFile(full, bytes);
}

function setStatus(ctx: AgentContext, projectId: string, shotId: string, status: ShotStatus, patch: Partial<Shot> = {}): Shot {
  const plan = ctx.repo.getShotPlan(projectId);
  if (!plan) throw new Error("no shot plan");
  let updated: Shot | undefined;
  const shots = plan.shots.map((s) => {
    if (s.id !== shotId) return s;
    updated = { ...s, ...patch, status };
    return updated;
  });
  ctx.repo.saveShotPlan({ ...plan, shots });
  if (!updated) throw new Error(`shot ${shotId} not found`);
  return updated;
}

export interface CharacterReference {
  characterId: string;
  path: string;
  mimeType: string;
  prompt: string;
  provenance: MediaAsset["provenance"];
}

/**
 * Character reference sheets: one canonical image per character, generated from the character bible
 * (appearance, clothing, style guide) and passed as a reference to every keyframe request that
 * includes the character. This anchors identity across shots when the image model supports references.
 */
export async function ensureCharacterReferences(ctx: AgentContext, project: Project): Promise<CharacterReference[]> {
  const { repo, media, events, config } = ctx;
  const world = repo.getWorld(project.id);
  if (!world) return [];
  const refs: CharacterReference[] = [];
  for (const c of world.characters) {
    const existing = repo.store.get<CharacterReference>("character_refs", project.id, c.id);
    if (existing) {
      refs.push(existing);
      continue;
    }
    const constraints = world.visualConstraints.filter((v) => v.entityId === c.id).map((v) => v.promptKeywords[0] ?? v.value);
    const prompt = `${project.brief.visualStyle}. Character reference sheet for ${c.name}: ${c.appearance.summary ?? c.description}; wearing ${c.clothing.summary ?? (c.clothing.items.join(", ") || "as established")}. Front view, neutral pose, full body, plain background, clear lighting.${constraints.length ? ` Must show: ${constraints.join("; ")}.` : ""}${world.styleGuide ? ` Style guide: ${world.styleGuide}` : ""} No text, no watermark.`;
    try {
      const image = await media.generateImage({ prompt, aspectRatio: "1:1", label: `${c.name} · reference` });
      const path = `${project.id}/references/${c.id}.${EXT[image.mimeType] ?? "bin"}`;
      await writeAsset(config.mediaDir, path, image.bytes);
      const ref: CharacterReference = { characterId: c.id, path, mimeType: image.mimeType, prompt, provenance: image.provenance };
      repo.store.put("character_refs", project.id, c.id, ref);
      await ctx.memory.recordGenerationAttempt({ projectId: project.id, shotId: `ref:${c.id}`, attempt: 1, kind: "reference", provider: image.provenance.provider, model: image.provenance.model, path, ok: true, latencyMs: image.provenance.latencyMs, createdAt: new Date().toISOString() }).catch(() => undefined);
      refs.push(ref);
      events.emit(project.id, "generation", "character.reference.generated", `Reference sheet for ${c.name} generated by ${image.provenance.provider}${image.provenance.provider === "placeholder" ? " (placeholder, not AI output)" : ""}`, { characterId: c.id, path, provenance: image.provenance });
    } catch (e) {
      events.emit(project.id, "generation", "character.reference.failed", `Reference sheet for ${c.name} failed: ${(e as Error).message}`, { characterId: c.id }, "warn");
    }
  }
  return refs;
}

export function listCharacterReferences(ctx: AgentContext, projectId: string): CharacterReference[] {
  return ctx.repo.store.list<CharacterReference>("character_refs", projectId);
}

export const UPLOAD_NOTE = "Uploaded by the user (a photo or drawing of the real person). Used as the identity reference for every keyframe with this character; never generated by a model.";
const UPLOAD_MIME = new Set(["image/png", "image/jpeg", "image/webp"]);

/**
 * Personalised references: a parent or therapist uploads a photo/drawing of the child (or a companion) and it replaces
 * the generated reference sheet as the identity anchor for every shot with that character.
 */
export async function saveUploadedReference(ctx: AgentContext, project: Project, characterId: string, file: { mimeType: string; data: string }, uploadedBy?: string, kind: "character" | "location" = "character"): Promise<CharacterReference> {
  const { repo, config, events } = ctx;
  const world = repo.getWorld(project.id);
  const brief = project.socialStory;
  const known =
    kind === "location"
      ? world
        ? world.locations.some((l) => l.id === characterId)
        : !!brief && brief.settings.some((s) => s.id === characterId)
      : world
        ? world.characters.some((c) => c.id === characterId)
        : !!brief && (slugify(brief.child.name) === characterId || brief.companions.some((c) => c.id === characterId));
  if (!known) throw new Error(`${kind === "location" ? "Setting" : "Character"} ${characterId} is not part of this project${world ? "" : " (run source analysis first)"}`);
  const collection = kind === "location" ? "location_refs" : "character_refs";
  if (!UPLOAD_MIME.has(file.mimeType)) throw new Error(`Unsupported image type ${file.mimeType} (use PNG, JPEG or WebP)`);
  const bytes = Buffer.from(file.data, "base64");
  if (bytes.length === 0) throw new Error("Empty image");
  if (bytes.length > 8 * 1024 * 1024) throw new Error("Image larger than 8 MB");
  const path = `${project.id}/references/${characterId}_upload.${EXT[file.mimeType] ?? "bin"}`;
  await writeAsset(config.mediaDir, path, bytes);
  const ref: CharacterReference = { characterId, path, mimeType: file.mimeType, prompt: "(uploaded reference image)", provenance: { provider: "upload", model: "user-photo", task: "reference", createdAt: new Date().toISOString(), note: UPLOAD_NOTE } };
  repo.store.put(collection, project.id, characterId, ref);
  await ctx.memory.recordGenerationAttempt({ projectId: project.id, shotId: `ref:${characterId}`, attempt: 1, kind: "reference", provider: "upload", model: "user-photo", path, ok: true, createdAt: new Date().toISOString() }).catch(() => undefined);
  const name = (kind === "location" ? world?.locations.find((l) => l.id === characterId)?.name : world?.characters.find((c) => c.id === characterId)?.name) ?? characterId;
  events.emit(project.id, "user", kind === "location" ? "location.reference.uploaded" : "character.reference.uploaded", `${kind === "location" ? "Photo of the real place" : "Reference photo"} uploaded for ${name}${uploadedBy ? ` by ${uploadedBy}` : ""} (${Math.round(bytes.length / 1024)} KB); it now anchors every keyframe ${kind === "location" ? "set there" : `with ${name}`}`, { characterId, kind, path, bytes: bytes.length });
  return ref;
}

export function listLocationReferences(ctx: AgentContext, projectId: string): CharacterReference[] {
  return ctx.repo.store.list<CharacterReference>("location_refs", projectId);
}

export function removeCharacterReference(ctx: AgentContext, projectId: string, characterId: string, kind: "character" | "location" = "character"): boolean {
  const collection = kind === "location" ? "location_refs" : "character_refs";
  const existing = ctx.repo.store.get<CharacterReference>(collection, projectId, characterId);
  if (!existing) return false;
  ctx.repo.store.delete(collection, projectId, characterId);
  ctx.events.emit(projectId, "user", "character.reference.removed", `Reference for ${characterId} removed (${existing.provenance.provider}); the next generation will create a new reference sheet`, { characterId });
  return true;
}

export interface GenerateOptions {
  reason?: string;
  /** Skip video even if the provider supports it. */
  keyframeOnly?: boolean;
}

/**
 * Generation Service: produces a keyframe (always), a voice track for the shot's lines (when the
 * provider supports speech) and a video clip (when enabled). Shot status transitions are persisted
 * and every asset records the provider/model that produced it.
 */
export async function generateShotMedia(ctx: AgentContext, project: Project, shotId: string, opts: GenerateOptions = {}): Promise<Shot> {
  const { repo, media, events, config } = ctx;
  const plan = repo.getShotPlan(project.id);
  const shot = plan?.shots.find((s) => s.id === shotId);
  if (!shot) throw new Error(`Shot ${shotId} not found`);
  const world = repo.getWorld(project.id);
  const attempt = shot.generationAttempts + 1;
  setStatus(ctx, project.id, shotId, "GENERATING", { generationAttempts: attempt, lastError: undefined });
  events.emit(project.id, "generation", "shot.generation.started", `Generating ${shotId}${opts.reason ? ` (${opts.reason})` : ""} with ${media.name}`, { shotId, attempt, provider: media.name });

  try {
    // Keyframe: identity references for every character, plus a real-place reference for the setting when one was uploaded.
    const references = [] as Array<{ mimeType: string; data: string; label: string }>;
    const addRef = async (ref: CharacterReference | undefined, label: string) => {
      // Placeholder cards are not real references; only pass model-generated or uploaded images.
      if (!ref || ref.provenance.provider === "placeholder") return;
      try {
        const bytes = await readFile(join(config.mediaDir, ref.path));
        references.push({ mimeType: ref.mimeType, data: bytes.toString("base64"), label });
      } catch {
        /* missing reference is fine */
      }
    };
    for (const cid of shot.characterIds) await addRef(repo.store.get<CharacterReference>("character_refs", project.id, cid), world?.characters.find((c) => c.id === cid)?.name ?? cid);
    await addRef(repo.store.get<CharacterReference>("location_refs", project.id, shot.locationId), `the real place: ${world?.locations.find((l) => l.id === shot.locationId)?.name ?? shot.locationId} (match this room)`);
    const t0 = Date.now();
    let image: Awaited<ReturnType<typeof media.generateImage>>;
    try {
      image = await media.generateImage({ prompt: shot.visualPrompt, negativePrompt: shot.negativePrompt, aspectRatio: "16:9", references, label: `${shotId} · Scene ${shot.sceneNumber}` });
    } catch (e) {
      await ctx.memory.recordGenerationAttempt({ projectId: project.id, shotId, attempt, kind: "keyframe", provider: media.name, ok: false, error: (e as Error).message, latencyMs: Date.now() - t0, createdAt: new Date().toISOString() }).catch(() => undefined);
      throw e;
    }
    const keyPath = `${project.id}/${shotId}/keyframe_v${attempt}.${EXT[image.mimeType] ?? "bin"}`;
    await writeAsset(config.mediaDir, keyPath, image.bytes);
    await ctx.memory.recordGenerationAttempt({ projectId: project.id, shotId, attempt, kind: "keyframe", provider: image.provenance.provider, model: image.provenance.model, path: keyPath, ok: true, latencyMs: image.provenance.latencyMs ?? Date.now() - t0, createdAt: new Date().toISOString() }).catch(() => undefined);
    const keyframe: MediaAsset = { kind: "image", path: keyPath, mimeType: image.mimeType, width: image.width, height: image.height, provenance: image.provenance, prompt: shot.visualPrompt };
    events.emit(project.id, "generation", "shot.keyframe.generated", `${shotId} keyframe generated by ${image.provenance.provider}${image.provenance.model ? `/${image.provenance.model}` : ""}${image.provenance.provider === "placeholder" ? " (placeholder, not AI output)" : ""}`, { shotId, path: keyPath, provenance: image.provenance });

    // Voice
    let audio: MediaAsset | undefined;
    const spoken = shot.dialogue.filter((d) => d.text.trim());
    if (media.capabilities.speech && spoken.length) {
      try {
        const speaker = spoken[0].characterId ? world?.characters.find((c) => c.id === spoken[0].characterId) : undefined;
        const text = spoken.map((d) => d.text).join(" ");
        const speech = await media.generateSpeech({ text, voiceDescription: speaker?.voice.description, language: project.brief.language });
        const audioPath = `${project.id}/${shotId}/voice_v${attempt}.${EXT[speech.mimeType] ?? "bin"}`;
        await writeAsset(config.mediaDir, audioPath, speech.bytes);
        audio = { kind: "audio", path: audioPath, mimeType: speech.mimeType, durationSec: speech.durationSec, provenance: speech.provenance, prompt: text };
        await ctx.memory.recordGenerationAttempt({ projectId: project.id, shotId, attempt, kind: "audio", provider: speech.provenance.provider, model: speech.provenance.model, path: audioPath, ok: true, latencyMs: speech.provenance.latencyMs, createdAt: new Date().toISOString() }).catch(() => undefined);
        events.emit(project.id, "generation", "shot.voice.generated", `${shotId} voice track generated (${speech.provenance.model})`, { shotId, path: audioPath });
      } catch (e) {
        await ctx.memory.recordGenerationAttempt({ projectId: project.id, shotId, attempt, kind: "audio", provider: media.name, ok: false, error: (e as Error).message, createdAt: new Date().toISOString() }).catch(() => undefined);
        events.emit(project.id, "generation", "shot.voice.failed", `${shotId} voice generation failed: ${(e as Error).message}`, { shotId }, "warn");
      }
    }

    // Video
    let video: MediaAsset | undefined;
    if (media.capabilities.video && (config.enableVideoGeneration || project.video) && !opts.keyframeOnly) {
      try {
        const clip = await media.generateVideo({ prompt: videoPrompt(project, shot), negativePrompt: shot.negativePrompt, durationSec: shot.durationSec, aspectRatio: "16:9", startImage: image.mimeType.startsWith("image/") && image.mimeType !== "image/svg+xml" ? { mimeType: image.mimeType, data: Buffer.from(image.bytes).toString("base64") } : undefined });
        const videoPath = `${project.id}/${shotId}/clip_v${attempt}.${EXT[clip.mimeType] ?? "mp4"}`;
        await writeAsset(config.mediaDir, videoPath, clip.bytes);
        video = { kind: "video", path: videoPath, mimeType: clip.mimeType, durationSec: clip.durationSec, provenance: clip.provenance, prompt: shot.visualPrompt };
        await ctx.memory.recordGenerationAttempt({ projectId: project.id, shotId, attempt, kind: "video", provider: clip.provenance.provider, model: clip.provenance.model, path: videoPath, ok: true, latencyMs: clip.provenance.latencyMs, createdAt: new Date().toISOString() }).catch(() => undefined);
        events.emit(project.id, "generation", "shot.video.generated", `${shotId} video clip generated (${clip.provenance.model})`, { shotId, path: videoPath });
      } catch (e) {
        await ctx.memory.recordGenerationAttempt({ projectId: project.id, shotId, attempt, kind: "video", provider: media.name, ok: false, error: (e as Error).message, createdAt: new Date().toISOString() }).catch(() => undefined);
        if (e instanceof MediaUnavailableError) events.emit(project.id, "generation", "shot.video.unavailable", `${shotId} video not generated: ${e.message}`, { shotId }, "warn");
        else throw e;
      }
    }

    const done = setStatus(ctx, project.id, shotId, "VERIFYING", { keyframe, audio: audio ?? shot.audio, video: video ?? shot.video, lastError: undefined });
    await ctx.memory.recordShots(repo.getShotPlan(project.id)!).catch(() => undefined);
    events.emit(project.id, "generation", "shot.generation.completed", `Shot ${shotId} generated`, { shotId, attempt }, "success");
    return done;
  } catch (err) {
    const msg = (err as Error).message;
    setStatus(ctx, project.id, shotId, "FAILED", { lastError: msg });
    events.emit(project.id, "generation", "shot.generation.failed", `Shot ${shotId} generation failed: ${msg}`, { shotId, attempt }, "error");
    throw err;
  }
}

/** The clip starts from the verified keyframe; for social stories the motion must be minimal so nothing new appears. */
export function videoPrompt(project: Project, shot: Shot): string {
  const calm = project.mode === "social_story" ? " Very gentle, minimal motion only: small natural movements, slow breathing, a glance, a hand moving slightly. Static camera, no cuts, no zoom, nobody enters or leaves, nothing new appears, no text or captions." : "";
  return `${shot.visualPrompt}${calm}`;
}

/**
 * Add a moving clip to a shot that already has a verified keyframe (start frame = that keyframe), without redoing the
 * picture or the voice. Used when a family asks for video after the pictures were approved, or to fill in clips.
 */
export async function generateShotVideo(ctx: AgentContext, project: Project, shotId: string): Promise<Shot> {
  const { repo, media, events, config } = ctx;
  const plan = repo.getShotPlan(project.id);
  const shot = plan?.shots.find((s) => s.id === shotId);
  if (!shot) throw new Error(`Shot ${shotId} not found`);
  if (!shot.keyframe || shot.keyframe.provenance.provider === "placeholder") throw new MediaUnavailableError(`Shot ${shotId} has no generated keyframe to start the clip from`);
  if (!media.capabilities.video) throw new MediaUnavailableError(`${media.name} cannot generate video`);
  const attempt = shot.generationAttempts;
  const t0 = Date.now();
  events.emit(project.id, "generation", "shot.video.started", `Generating a clip for ${shotId} from its verified keyframe (${media.name})`, { shotId });
  try {
    const bytes = await readFile(join(config.mediaDir, shot.keyframe.path));
    const clip = await media.generateVideo({ prompt: videoPrompt(project, shot), negativePrompt: shot.negativePrompt, durationSec: shot.durationSec, aspectRatio: "16:9", startImage: { mimeType: shot.keyframe.mimeType, data: bytes.toString("base64") } });
    const videoPath = `${project.id}/${shotId}/clip_v${attempt}.${EXT[clip.mimeType] ?? "mp4"}`;
    await writeAsset(config.mediaDir, videoPath, clip.bytes);
    const video: MediaAsset = { kind: "video", path: videoPath, mimeType: clip.mimeType, durationSec: clip.durationSec, provenance: clip.provenance, prompt: videoPrompt(project, shot) };
    await ctx.memory.recordGenerationAttempt({ projectId: project.id, shotId, attempt, kind: "video", provider: clip.provenance.provider, model: clip.provenance.model, path: videoPath, ok: true, latencyMs: clip.provenance.latencyMs ?? Date.now() - t0, createdAt: new Date().toISOString() }).catch(() => undefined);
    const updated = setStatus(ctx, project.id, shotId, shot.status, { video });
    await ctx.memory.recordShots(repo.getShotPlan(project.id)!).catch(() => undefined);
    events.emit(project.id, "generation", "shot.video.generated", `${shotId} clip generated (${clip.provenance.model}, ${clip.durationSec ?? "?"}s, ${Math.round((Date.now() - t0) / 1000)}s)`, { shotId, path: videoPath, provenance: clip.provenance }, "success");
    return updated;
  } catch (e) {
    await ctx.memory.recordGenerationAttempt({ projectId: project.id, shotId, attempt, kind: "video", provider: media.name, ok: false, error: (e as Error).message, latencyMs: Date.now() - t0, createdAt: new Date().toISOString() }).catch(() => undefined);
    events.emit(project.id, "generation", "shot.video.failed", `${shotId} clip failed: ${(e as Error).message}`, { shotId }, "error");
    throw e;
  }
}

/** Clips for every shot that has a keyframe but no clip. Continues past individual failures and reports them. */
export async function generateAllVideos(ctx: AgentContext, project: Project): Promise<{ generated: string[]; failed: Array<{ shotId: string; error: string }> }> {
  const plan = ctx.repo.getShotPlan(project.id);
  if (!plan) throw new Error("Shots must be planned before generation");
  const generated: string[] = [];
  const failed: Array<{ shotId: string; error: string }> = [];
  for (const shot of plan.shots) {
    if (shot.video || !shot.keyframe) continue;
    try {
      await generateShotVideo(ctx, project, shot.id);
      generated.push(shot.id);
    } catch (e) {
      failed.push({ shotId: shot.id, error: (e as Error).message });
    }
  }
  ctx.events.emit(project.id, "generation", "video.summary", `Clips: ${generated.length} generated, ${failed.length} failed`, { generated, failed }, failed.length ? "warn" : "success");
  return { generated, failed };
}

/** Generate media for every shot that has none (or is PLANNED/FAILED). Continues past individual failures and reports them. */
export async function generateAllMedia(ctx: AgentContext, project: Project, opts: GenerateOptions = {}): Promise<{ generated: string[]; failed: Array<{ shotId: string; error: string }> }> {
  const plan = ctx.repo.getShotPlan(project.id);
  if (!plan) throw new Error("Shots must be planned before generation");
  await ensureCharacterReferences(ctx, project);
  const generated: string[] = [];
  const failed: Array<{ shotId: string; error: string }> = [];
  for (const shot of plan.shots) {
    if (shot.keyframe && shot.status !== "PLANNED" && shot.status !== "FAILED") continue;
    try {
      await generateShotMedia(ctx, project, shot.id, opts);
      generated.push(shot.id);
    } catch (e) {
      failed.push({ shotId: shot.id, error: (e as Error).message });
    }
  }
  return { generated, failed };
}

/** After visual verification, mark shots VERIFIED or FAILED based on open violations against them. */
export function applyVerificationToShots(ctx: AgentContext, projectId: string): { verified: number; failed: number } {
  const plan = ctx.repo.getShotPlan(projectId);
  if (!plan) return { verified: 0, failed: 0 };
  const open = ctx.repo.listViolations(projectId).filter((v) => v.critic === "visual" && (v.status === "open" || v.status === "repairing" || v.status === "escalated"));
  let verified = 0;
  let failed = 0;
  const shots = plan.shots.map((s) => {
    if (!s.keyframe) return s;
    const bad = open.some((v) => v.scope.shotId === s.id);
    if (bad) failed += 1;
    else verified += 1;
    return { ...s, status: (bad ? "FAILED" : "VERIFIED") as ShotStatus };
  });
  ctx.repo.saveShotPlan({ ...plan, shots });
  void ctx.memory.recordShots({ ...plan, shots }).catch(() => undefined);
  return { verified, failed };
}
