import { mkdir, writeFile, readFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import type { AgentContext } from "../agents/context.js";
import type { MediaAsset, Project, Shot, ShotStatus } from "../model/index.js";
import { MediaUnavailableError } from "./provider.js";

const EXT: Record<string, string> = { "image/png": "png", "image/jpeg": "jpg", "image/svg+xml": "svg", "image/webp": "webp", "video/mp4": "mp4", "audio/wav": "wav", "audio/mpeg": "mp3" };

async function writeAsset(mediaDir: string, relPath: string, bytes: Uint8Array): Promise<void> {
  const full = join(mediaDir, relPath);
  await mkdir(dirname(full), { recursive: true });
  await writeFile(full, bytes);
}

function setStatus(ctx: AgentContext, projectId: string, shotId: string, status: ShotStatus, patch: Partial<Shot> = {}): Shot {
  const plan = ctx.repo.getShotPlan(projectId);
  if (!plan) throw new Error("no shot plan");
  let updated: Shot | undefined;
  const shots = plan.shots.map((s) => {
    if (s.id !== shotId) return s;
    updated = { ...s, ...patch, status };
    return updated;
  });
  ctx.repo.saveShotPlan({ ...plan, shots });
  if (!updated) throw new Error(`shot ${shotId} not found`);
  return updated;
}

export interface CharacterReference {
  characterId: string;
  path: string;
  mimeType: string;
  prompt: string;
  provenance: MediaAsset["provenance"];
}

/**
 * Character reference sheets: one canonical image per character, generated from the character bible
 * (appearance, clothing, style guide) and passed as a reference to every keyframe request that
 * includes the character. This anchors identity across shots when the image model supports references.
 */
export async function ensureCharacterReferences(ctx: AgentContext, project: Project): Promise<CharacterReference[]> {
  const { repo, media, events, config } = ctx;
  const world = repo.getWorld(project.id);
  if (!world) return [];
  const refs: CharacterReference[] = [];
  for (const c of world.characters) {
    const existing = repo.store.get<CharacterReference>("character_refs", project.id, c.id);
    if (existing) {
      refs.push(existing);
      continue;
    }
    const constraints = world.visualConstraints.filter((v) => v.entityId === c.id).map((v) => v.promptKeywords[0] ?? v.value);
    const prompt = `${project.brief.visualStyle}. Character reference sheet for ${c.name}: ${c.appearance.summary ?? c.description}; wearing ${c.clothing.summary ?? (c.clothing.items.join(", ") || "as established")}. Front view, neutral pose, full body, plain background, clear lighting.${constraints.length ? ` Must show: ${constraints.join("; ")}.` : ""}${world.styleGuide ? ` Style guide: ${world.styleGuide}` : ""} No text, no watermark.`;
    try {
      const image = await media.generateImage({ prompt, aspectRatio: "1:1", label: `${c.name} · reference` });
      const path = `${project.id}/references/${c.id}.${EXT[image.mimeType] ?? "bin"}`;
      await writeAsset(config.mediaDir, path, image.bytes);
      const ref: CharacterReference = { characterId: c.id, path, mimeType: image.mimeType, prompt, provenance: image.provenance };
      repo.store.put("character_refs", project.id, c.id, ref);
      refs.push(ref);
      events.emit(project.id, "generation", "character.reference.generated", `Reference sheet for ${c.name} generated by ${image.provenance.provider}${image.provenance.provider === "placeholder" ? " (placeholder, not AI output)" : ""}`, { characterId: c.id, path, provenance: image.provenance });
    } catch (e) {
      events.emit(project.id, "generation", "character.reference.failed", `Reference sheet for ${c.name} failed: ${(e as Error).message}`, { characterId: c.id }, "warn");
    }
  }
  return refs;
}

export function listCharacterReferences(ctx: AgentContext, projectId: string): CharacterReference[] {
  return ctx.repo.store.list<CharacterReference>("character_refs", projectId);
}

export interface GenerateOptions {
  reason?: string;
  /** Skip video even if the provider supports it. */
  keyframeOnly?: boolean;
}

/**
 * Generation Service: produces a keyframe (always), a voice track for the shot's lines (when the
 * provider supports speech) and a video clip (when enabled). Shot status transitions are persisted
 * and every asset records the provider/model that produced it.
 */
export async function generateShotMedia(ctx: AgentContext, project: Project, shotId: string, opts: GenerateOptions = {}): Promise<Shot> {
  const { repo, media, events, config } = ctx;
  const plan = repo.getShotPlan(project.id);
  const shot = plan?.shots.find((s) => s.id === shotId);
  if (!shot) throw new Error(`Shot ${shotId} not found`);
  const world = repo.getWorld(project.id);
  const attempt = shot.generationAttempts + 1;
  setStatus(ctx, project.id, shotId, "GENERATING", { generationAttempts: attempt, lastError: undefined });
  events.emit(project.id, "generation", "shot.generation.started", `Generating ${shotId}${opts.reason ? ` (${opts.reason})` : ""} with ${media.name}`, { shotId, attempt, provider: media.name });

  try {
    // Keyframe
    const references = [] as Array<{ mimeType: string; data: string; label: string }>;
    for (const cid of shot.characterIds) {
      const ref = repo.store.get<CharacterReference>("character_refs", project.id, cid);
      // Placeholder cards are not real references; only pass model-generated images.
      if (ref && ref.provenance.provider !== "placeholder") {
        try {
          const bytes = await readFile(join(config.mediaDir, ref.path));
          references.push({ mimeType: ref.mimeType, data: bytes.toString("base64"), label: world?.characters.find((c) => c.id === cid)?.name ?? cid });
        } catch {
          /* missing reference is fine */
        }
      }
    }
    const image = await media.generateImage({ prompt: shot.visualPrompt, negativePrompt: shot.negativePrompt, aspectRatio: "16:9", references, label: `${shotId} · Scene ${shot.sceneNumber}` });
    const keyPath = `${project.id}/${shotId}/keyframe_v${attempt}.${EXT[image.mimeType] ?? "bin"}`;
    await writeAsset(config.mediaDir, keyPath, image.bytes);
    const keyframe: MediaAsset = { kind: "image", path: keyPath, mimeType: image.mimeType, width: image.width, height: image.height, provenance: image.provenance, prompt: shot.visualPrompt };
    events.emit(project.id, "generation", "shot.keyframe.generated", `${shotId} keyframe generated by ${image.provenance.provider}${image.provenance.model ? `/${image.provenance.model}` : ""}${image.provenance.provider === "placeholder" ? " (placeholder, not AI output)" : ""}`, { shotId, path: keyPath, provenance: image.provenance });

    // Voice
    let audio: MediaAsset | undefined;
    const spoken = shot.dialogue.filter((d) => d.text.trim());
    if (media.capabilities.speech && spoken.length) {
      try {
        const speaker = spoken[0].characterId ? world?.characters.find((c) => c.id === spoken[0].characterId) : undefined;
        const text = spoken.map((d) => d.text).join(" ");
        const speech = await media.generateSpeech({ text, voiceDescription: speaker?.voice.description, language: project.brief.language });
        const audioPath = `${project.id}/${shotId}/voice_v${attempt}.${EXT[speech.mimeType] ?? "bin"}`;
        await writeAsset(config.mediaDir, audioPath, speech.bytes);
        audio = { kind: "audio", path: audioPath, mimeType: speech.mimeType, durationSec: speech.durationSec, provenance: speech.provenance, prompt: text };
        events.emit(project.id, "generation", "shot.voice.generated", `${shotId} voice track generated (${speech.provenance.model})`, { shotId, path: audioPath });
      } catch (e) {
        events.emit(project.id, "generation", "shot.voice.failed", `${shotId} voice generation failed: ${(e as Error).message}`, { shotId }, "warn");
      }
    }

    // Video
    let video: MediaAsset | undefined;
    if (media.capabilities.video && config.enableVideoGeneration && !opts.keyframeOnly) {
      try {
        const clip = await media.generateVideo({ prompt: shot.visualPrompt, negativePrompt: shot.negativePrompt, durationSec: shot.durationSec, aspectRatio: "16:9", startImage: image.mimeType.startsWith("image/") && image.mimeType !== "image/svg+xml" ? { mimeType: image.mimeType, data: Buffer.from(image.bytes).toString("base64") } : undefined });
        const videoPath = `${project.id}/${shotId}/clip_v${attempt}.${EXT[clip.mimeType] ?? "mp4"}`;
        await writeAsset(config.mediaDir, videoPath, clip.bytes);
        video = { kind: "video", path: videoPath, mimeType: clip.mimeType, durationSec: clip.durationSec, provenance: clip.provenance, prompt: shot.visualPrompt };
        events.emit(project.id, "generation", "shot.video.generated", `${shotId} video clip generated (${clip.provenance.model})`, { shotId, path: videoPath });
      } catch (e) {
        if (e instanceof MediaUnavailableError) events.emit(project.id, "generation", "shot.video.unavailable", `${shotId} video not generated: ${e.message}`, { shotId }, "warn");
        else throw e;
      }
    }

    const done = setStatus(ctx, project.id, shotId, "VERIFYING", { keyframe, audio: audio ?? shot.audio, video: video ?? shot.video, lastError: undefined });
    events.emit(project.id, "generation", "shot.generation.completed", `Shot ${shotId} generated`, { shotId, attempt }, "success");
    return done;
  } catch (err) {
    const msg = (err as Error).message;
    setStatus(ctx, project.id, shotId, "FAILED", { lastError: msg });
    events.emit(project.id, "generation", "shot.generation.failed", `Shot ${shotId} generation failed: ${msg}`, { shotId, attempt }, "error");
    throw err;
  }
}

/** Generate media for every shot that has none (or is PLANNED/FAILED). Continues past individual failures and reports them. */
export async function generateAllMedia(ctx: AgentContext, project: Project, opts: GenerateOptions = {}): Promise<{ generated: string[]; failed: Array<{ shotId: string; error: string }> }> {
  const plan = ctx.repo.getShotPlan(project.id);
  if (!plan) throw new Error("Shots must be planned before generation");
  await ensureCharacterReferences(ctx, project);
  const generated: string[] = [];
  const failed: Array<{ shotId: string; error: string }> = [];
  for (const shot of plan.shots) {
    if (shot.keyframe && shot.status !== "PLANNED" && shot.status !== "FAILED") continue;
    try {
      await generateShotMedia(ctx, project, shot.id, opts);
      generated.push(shot.id);
    } catch (e) {
      failed.push({ shotId: shot.id, error: (e as Error).message });
    }
  }
  return { generated, failed };
}

/** After visual verification, mark shots VERIFIED or FAILED based on open violations against them. */
export function applyVerificationToShots(ctx: AgentContext, projectId: string): { verified: number; failed: number } {
  const plan = ctx.repo.getShotPlan(projectId);
  if (!plan) return { verified: 0, failed: 0 };
  const open = ctx.repo.listViolations(projectId).filter((v) => v.critic === "visual" && (v.status === "open" || v.status === "repairing" || v.status === "escalated"));
  let verified = 0;
  let failed = 0;
  const shots = plan.shots.map((s) => {
    if (!s.keyframe) return s;
    const bad = open.some((v) => v.scope.shotId === s.id);
    if (bad) failed += 1;
    else verified += 1;
    return { ...s, status: (bad ? "FAILED" : "VERIFIED") as ShotStatus };
  });
  ctx.repo.saveShotPlan({ ...plan, shots });
  return { verified, failed };
}
