import type { GeneratedMedia, ImageRequest, MediaGenerationProvider, SpeechRequest, VideoRequest } from "./provider.js";
import { MediaUnavailableError } from "./provider.js";

export const PLACEHOLDER_NOTE = "DEVELOPMENT PLACEHOLDER: storyboard card rendered locally from the shot prompt. Not generated by an AI model.";

function esc(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function wrap(text: string, width: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    if ((cur + " " + w).trim().length > width) {
      if (cur) lines.push(cur);
      cur = w;
    } else cur = (cur + " " + w).trim();
  }
  if (cur) lines.push(cur);
  return lines;
}

/**
 * Placeholder provider for development without media credentials.
 * Produces an SVG storyboard card that is visibly labelled as a placeholder. It never claims to be model output,
 * and the Visual Critic refuses to inspect it (recorded as not_evaluated).
 */
export class PlaceholderMediaProvider implements MediaGenerationProvider {
  readonly name = "placeholder";
  readonly capabilities = { image: true, video: false, speech: false };

  async generateImage(req: ImageRequest): Promise<GeneratedMedia> {
    const w = 1280;
    const h = 720;
    const lines = wrap(req.prompt, 92).slice(0, 14);
    const body = lines.map((l, i) => `<text x="48" y="${150 + i * 30}" font-size="20" fill="#d7dbe0" font-family="Inter, Helvetica, Arial, sans-serif">${esc(l)}</text>`).join("");
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#101827"/><stop offset="1" stop-color="#1f2a44"/></linearGradient></defs>
<rect width="${w}" height="${h}" fill="url(#g)"/>
<rect x="24" y="24" width="${w - 48}" height="${h - 48}" fill="none" stroke="#f5b942" stroke-width="3" stroke-dasharray="14 10"/>
<text x="48" y="80" font-size="34" font-weight="700" fill="#f5b942" font-family="Inter, Helvetica, Arial, sans-serif">${esc(req.label ?? "SHOT")} — DEV PLACEHOLDER</text>
<text x="48" y="112" font-size="18" fill="#9aa4b2" font-family="Inter, Helvetica, Arial, sans-serif">Not AI-generated. Configure MEDIA_PROVIDER=gemini to render real keyframes.</text>
${body}
<text x="48" y="${h - 44}" font-size="16" fill="#6b7686" font-family="Inter, Helvetica, Arial, sans-serif">CineMemory placeholder · prompt length ${req.prompt.length} chars</text>
</svg>`;
    return {
      kind: "image",
      mimeType: "image/svg+xml",
      bytes: new TextEncoder().encode(svg),
      width: w,
      height: h,
      provenance: { provider: this.name, model: "svg-card", task: "keyframe", createdAt: new Date().toISOString(), note: PLACEHOLDER_NOTE },
    };
  }

  async generateVideo(_req: VideoRequest): Promise<GeneratedMedia> {
    throw new MediaUnavailableError("Placeholder provider cannot generate video. Configure MEDIA_PROVIDER=gemini.");
  }

  async generateSpeech(_req: SpeechRequest): Promise<GeneratedMedia> {
    throw new MediaUnavailableError("Placeholder provider cannot generate speech. Configure MEDIA_PROVIDER=gemini.");
  }
}
