import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from "pdf-lib";
import { buildContinuityCertificate, type AgentContext } from "@cinememory/core";

const A4 = { w: 595.28, h: 841.89 };
const M = 48;

function wrap(text: string, font: PDFFont, size: number, width: number): string[] {
  const out: string[] = [];
  for (const para of text.split("\n")) {
    let line = "";
    for (const word of para.split(/\s+/)) {
      const next = line ? `${line} ${word}` : word;
      if (font.widthOfTextAtSize(next, size) > width && line) {
        out.push(line);
        line = word;
      } else line = next;
    }
    out.push(line);
  }
  return out;
}

function text(page: PDFPage, font: PDFFont, size: number, x: number, y: number, lines: string[], color = rgb(0.12, 0.12, 0.14), leading = 1.35): number {
  let cy = y;
  for (const l of lines) {
    page.drawText(l, { x, y: cy, size, font, color });
    cy -= size * leading;
  }
  return cy;
}

/**
 * Printable booklet: the verified pictures with the authored words, one step per page, plus a cover that states the
 * certificate status and who approved it. Many therapists still use paper; this makes the film optional.
 */
export async function renderBooklet(ctx: AgentContext, projectId: string): Promise<Uint8Array> {
  const cert = await buildContinuityCertificate(ctx, projectId);
  const project = ctx.repo.getProject(projectId)!;
  const pdf = await PDFDocument.create();
  pdf.setTitle(`${cert.title} (social story)`);
  pdf.setAuthor(cert.authoredBy ?? "CineMemory");
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const reg = await pdf.embedFont(StandardFonts.Helvetica);
  const large = project.childId ? ctx.repo.getChild(project.childId)?.sensory.largeText : false;
  const bodySize = large ? 22 : 18;

  // Cover
  const cover = pdf.addPage([A4.w, A4.h]);
  let y = A4.h - M - 40;
  y = text(cover, bold, 30, M, y, wrap(cert.title, bold, 30, A4.w - 2 * M));
  y = text(cover, reg, 16, M, y - 6, [`A social story for ${cert.child}`, cert.situation], rgb(0.3, 0.3, 0.35));
  y -= 20;
  const status = cert.status === "verified" ? "Every picture was checked against the locked rules: verified." : cert.status === "issues" ? "Some pictures still have problems. Do not use until fixed." : "Not all pictures are finished or checked yet.";
  y = text(cover, reg, 12, M, y, wrap(status, reg, 12, A4.w - 2 * M));
  y = text(cover, reg, 12, M, y, wrap(`Words unchanged: ${cert.wordsUnchanged ? "yes" : "no"} · Order kept: ${cert.sequence.ordered ? "yes" : "no"} · Checks passed: ${cert.totals.checksPassed}/${cert.totals.checksEvaluated}${cert.totals.regenerations ? ` · pictures regenerated: ${cert.totals.regenerations}` : ""}`, reg, 12, A4.w - 2 * M));
  y = text(cover, reg, 12, M, y, [cert.approval ? `Approved by ${cert.approval.approvedBy} on ${cert.approval.approvedAt.slice(0, 10)}${cert.approvalValid ? "" : " (approval no longer matches the current pictures)"}` : "Not yet approved by a parent or therapist."], cert.approval?.approvedBy && cert.approvalValid ? rgb(0.1, 0.45, 0.2) : rgb(0.6, 0.3, 0.05));
  if (cert.authoredBy) text(cover, reg, 11, M, y - 4, [`Written by ${cert.authoredBy}`], rgb(0.4, 0.4, 0.45));
  text(cover, reg, 9, M, M, [`Generated by CineMemory on ${cert.generatedAt.slice(0, 10)} · pictures by ${cert.media.references[0]?.provider === "upload" ? "the image model using uploaded references" : "the image model"} · a person who knows the child should read this first`], rgb(0.5, 0.5, 0.55));

  // One step per page
  for (const step of cert.steps) {
    const page = pdf.addPage([A4.w, A4.h]);
    let py = A4.h - M;
    py = text(page, bold, 14, M, py - 14, [`Step ${step.number} of ${cert.steps.length}`], rgb(0.45, 0.45, 0.5));
    py = text(page, bold, 22, M, py - 4, wrap(step.title, bold, 22, A4.w - 2 * M));
    const imgW = A4.w - 2 * M;
    const imgH = imgW * 9 / 16;
    if (step.keyframe && step.realFrame) {
      try {
        const bytes = await readFile(join(ctx.config.mediaDir, step.keyframe.path));
        const img = step.keyframe.mimeType === "image/png" ? await pdf.embedPng(bytes) : await pdf.embedJpg(bytes);
        const scale = Math.min(imgW / img.width, imgH / img.height);
        page.drawImage(img, { x: M, y: py - 8 - img.height * scale, width: img.width * scale, height: img.height * scale });
        py -= 8 + img.height * scale;
      } catch {
        page.drawRectangle({ x: M, y: py - 8 - imgH, width: imgW, height: imgH, borderColor: rgb(0.7, 0.7, 0.7), borderWidth: 1 });
        py -= 8 + imgH;
      }
    } else {
      page.drawRectangle({ x: M, y: py - 8 - imgH, width: imgW, height: imgH, borderColor: rgb(0.7, 0.7, 0.7), borderWidth: 1 });
      text(page, reg, 12, M + 16, py - 8 - imgH / 2, [step.keyframe ? "Picture is a development placeholder" : "Picture not made yet"], rgb(0.5, 0.5, 0.55));
      py -= 8 + imgH;
    }
    py = text(page, reg, bodySize, M, py - 28, wrap(step.text, reg, bodySize, A4.w - 2 * M), rgb(0.1, 0.1, 0.12), 1.45);
    const checks = Object.entries(step.categories).filter(([, v]) => v.state !== "n/a").map(([k, v]) => `${k.replace("_", " ")}: ${v.state === "pass" ? "ok" : v.state === "fail" ? "PROBLEM" : "not checked"}`);
    text(page, reg, 9, M, M, [`${step.settingName} · with ${step.present.join(", ")} · ${step.verified ? "verified" : "not verified"}${checks.length ? ` · ${checks.join(" · ")}` : ""}`], rgb(0.5, 0.5, 0.55));
  }

  // Calming rules page
  if (project.socialStory?.calmingRules.length) {
    const page = pdf.addPage([A4.w, A4.h]);
    let py = text(page, bold, 22, M, A4.h - M - 18, ["Things I can do"]);
    for (const r of project.socialStory.calmingRules) py = text(page, reg, bodySize, M, py - 14, wrap(`•  ${r}`, reg, bodySize, A4.w - 2 * M), rgb(0.1, 0.1, 0.12), 1.45);
  }
  return pdf.save();
}
