/**
 * OpenAPI description of the CineMemory API. Served at /api/openapi.json so the API can be registered
 * as an OpenAPI tool for a Google Cloud Agent Builder / Gemini Enterprise agent (or any other agent
 * framework): an external agent can create projects, run the pipeline, read continuity status and
 * trigger repairs through these operations.
 */
export function openApiDocument(baseUrl: string) {
  const projectParam = { name: "id", in: "path", required: true, schema: { type: "string" }, description: "Project id" };
  const job = { type: "object", properties: { id: { type: "string" }, projectId: { type: "string" }, kind: { type: "string" }, status: { type: "string", enum: ["running", "complete", "failed"] }, detail: { type: "string" }, error: { type: "string" } } };
  const stage = { type: "string", enum: ["source_analyzed", "adapted", "screenplay_written", "memory_built", "shots_planned", "narrative_verified", "media_generated", "visually_verified", "film_assembled"] };
  return {
    openapi: "3.0.3",
    info: { title: "CineMemory API", version: "0.1.0", description: "Memory & verification layer for agentic filmmaking. Structured world memory, screenplay/shot planning, continuity critics and autonomous repair." },
    servers: [{ url: baseUrl }],
    paths: {
      "/api/health": { get: { operationId: "getHealth", summary: "Runtime status: which LLM/media providers are live and whether development fixtures are in use.", responses: { "200": { description: "OK" } } } },
      "/api/projects": {
        get: { operationId: "listProjects", summary: "List projects with stage, counts and continuity summary.", responses: { "200": { description: "OK" } } },
        post: {
          operationId: "createProject",
          summary: "Create a project from source material and a production brief.",
          requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["title", "mode", "source", "brief"], properties: { title: { type: "string" }, mode: { type: "string", enum: ["creator", "kids", "social_story"] }, source: { type: "object", required: ["kind", "title", "text"], properties: { kind: { type: "string", enum: ["original", "public_domain", "licensed", "screenplay", "idea", "lesson", "social_story"] }, title: { type: "string" }, author: { type: "string" }, text: { type: "string" }, rightsNote: { type: "string" } } }, brief: { type: "object", required: ["genre", "audience", "targetDurationSec", "visualStyle"], properties: { genre: { type: "string" }, audience: { type: "string" }, ageRange: { type: "string" }, targetDurationSec: { type: "integer" }, language: { type: "string" }, visualStyle: { type: "string" }, tone: { type: "string" }, format: { type: "string" }, adaptationInstructions: { type: "string" }, requiredFacts: { type: "array", items: { type: "string" } } } }, socialStory: { type: "object", description: "Required for mode social_story: child {name, age, appearance, outfit}, situation, companions[], comfortItems[], settings[], steps[{title, text, settingId, companionIds, comfortItemIds, visual}], mustNotShow[], calmingRules[]" } } } } } },
          responses: { "201": { description: "Created" } },
        },
      },
      "/api/projects/social-story-demo": { post: { operationId: "createSocialStoryDemo", summary: "Create (or return) the bundled social-story demo 'Maya goes to the dentist'.", responses: { "201": { description: "Created" } } } },
      "/api/social-stories/draft": { post: { operationId: "draftSocialStory", summary: "Gemini-assisted first draft of a social story routine (steps, settings, companions, must-not-show list). The adult edits it before use.", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["situation", "childName"], properties: { situation: { type: "string" }, childName: { type: "string" }, childAge: { type: "string" }, notes: { type: "string" }, language: { type: "string" } } } } } }, responses: { "200": { description: "OK" }, "503": { description: "No Gemini key configured" } } } },
      "/api/projects/{id}/references/{characterId}": { post: { operationId: "uploadReference", summary: "Upload a photo/drawing (base64) as the identity reference for a character; it anchors every keyframe with that character.", parameters: [projectParam, { name: "characterId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["mimeType", "data"], properties: { mimeType: { type: "string", enum: ["image/png", "image/jpeg", "image/webp"] }, data: { type: "string", description: "base64" }, uploadedBy: { type: "string" } } } } } }, responses: { "201": { description: "Stored" } } }, delete: { operationId: "removeReference", summary: "Remove a character's reference image.", parameters: [projectParam, { name: "characterId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "OK" } } } },
      "/api/children": { get: { operationId: "listChildren", summary: "Child profiles (social stories): one canonical child reused by every story.", responses: { "200": { description: "OK" } } }, post: { operationId: "upsertChild", summary: "Create or update a child profile (look, one outfit, comfort items, companions, familiar places, sensory profile).", responses: { "201": { description: "Created" } } } },
      "/api/children/{id}": { get: { operationId: "getChild", summary: "Profile, its stories with outcomes, photos and the ClickHouse longitudinal history.", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "OK" } } } },
      "/api/children/{id}/brief": { post: { operationId: "briefFromChild", summary: "Merge a child's profile with story-specific steps into a full social-story brief.", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "OK" } } } },
      "/api/social-stories/lint": { post: { operationId: "lintSocialStory", summary: "Plain-language critic: first person, sentence length, tense, negatives, idioms, one idea per step.", responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/booklet.pdf": { get: { operationId: "getBooklet", summary: "Printable PDF booklet of the verified pictures with the authored words.", parameters: [projectParam], responses: { "200": { description: "PDF" } } } },
      "/api/projects/{id}/outcomes": { get: { operationId: "listOutcomes", summary: "What happened after the real visit.", parameters: [projectParam], responses: { "200": { description: "OK" } } }, post: { operationId: "recordOutcome", summary: "Record times watched, how the visit went and per-step reactions; stored in ClickHouse for the child's history.", parameters: [projectParam], responses: { "201": { description: "Created" } } } },
      "/api/projects/{id}/certificate": { get: { operationId: "getContinuityCertificate", summary: "Continuity Certificate for a social story: per-step identity/outfit/setting/comfort-item/forbidden-content verification, repairs, sequence and word integrity, approval state.", parameters: [projectParam], responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/approve": { post: { operationId: "approveSocialStory", summary: "Record a therapist/parent sign-off. Blocked (409) unless the certificate is verified, or force=true with a note.", parameters: [projectParam], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["approvedBy"], properties: { approvedBy: { type: "string" }, note: { type: "string" }, force: { type: "boolean" } } } } } }, responses: { "200": { description: "Approved" }, "409": { description: "Certificate not verified" } } }, delete: { operationId: "revokeApproval", summary: "Revoke the sign-off.", parameters: [projectParam], responses: { "200": { description: "OK" } } } },
      "/api/projects/demo": { post: { operationId: "createDemoProject", summary: "Create (or return) the bundled demo project.", responses: { "201": { description: "Created" } } } },
      "/api/projects/{id}": { get: { operationId: "getProject", summary: "Project dashboard summary.", parameters: [projectParam], responses: { "200": { description: "OK" } } }, delete: { operationId: "deleteProject", summary: "Delete a project and all its artifacts.", parameters: [projectParam], responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/run": { post: { operationId: "runPipeline", summary: "Run the agent pipeline up to a stage (resumable). Returns a job.", parameters: [projectParam], requestBody: { content: { "application/json": { schema: { type: "object", properties: { toStage: stage, force: { type: "boolean" } } } } } }, responses: { "202": { description: "Job started", content: { "application/json": { schema: job } } }, "409": { description: "A job is already running" } } } },
      "/api/projects/{id}/reset": { post: { operationId: "resetPipeline", summary: "Reset from a stage; downstream artifacts are discarded.", parameters: [projectParam], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["stage"], properties: { stage } } } } }, responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/verify": { post: { operationId: "runCritics", summary: "Re-run the continuity critics.", parameters: [projectParam], requestBody: { content: { "application/json": { schema: { type: "object", properties: { critics: { type: "array", items: { type: "string", enum: ["narrative", "source_fidelity", "visual"] } } } } } } }, responses: { "202": { description: "Job started" } } } },
      "/api/projects/{id}/job": { get: { operationId: "getJob", summary: "Current and recent jobs for the project.", parameters: [projectParam], responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/events": { get: { operationId: "listEvents", summary: "Workflow event log (real agent activity).", parameters: [projectParam, { name: "after", in: "query", schema: { type: "integer" } }], responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/world": { get: { operationId: "getWorldMemory", summary: "Canonical world state (characters, locations, props, events, knowledge facts, constraints).", parameters: [projectParam], responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/screenplay": { get: { operationId: "getScreenplay", summary: "Current screenplay with revision history.", parameters: [projectParam], responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/shots": { get: { operationId: "getShots", summary: "Shot plan with generation status and media.", parameters: [projectParam], responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/graph": { get: { operationId: "getCineGraph", summary: "CineGraph nodes and edges; optional focus node neighbourhood.", parameters: [projectParam, { name: "focus", in: "query", schema: { type: "string" } }, { name: "depth", in: "query", schema: { type: "integer" } }], responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/violations": { get: { operationId: "listViolations", summary: "All violations with status, evidence and repair attempts.", parameters: [projectParam], responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/continuity": { get: { operationId: "getContinuitySummary", summary: "Derived continuity scores (pass ÷ evaluated checks).", parameters: [projectParam], responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/violations/{vid}/repair": { post: { operationId: "repairViolation", summary: "Run the Repair Agent on one violation (bounded retries, escalates).", parameters: [projectParam, { name: "vid", in: "path", required: true, schema: { type: "string" } }], responses: { "202": { description: "Job started" } } } },
      "/api/projects/{id}/violations/{vid}/override": { post: { operationId: "overrideViolation", summary: "Manually accept a violation with a note.", parameters: [projectParam, { name: "vid", in: "path", required: true, schema: { type: "string" } }], requestBody: { content: { "application/json": { schema: { type: "object", properties: { note: { type: "string" } } } } } }, responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/shots/{shotId}/generate": { post: { operationId: "generateShot", summary: "(Re)generate one shot's media and re-run the Visual Critic.", parameters: [projectParam, { name: "shotId", in: "path", required: true, schema: { type: "string" } }], responses: { "202": { description: "Job started" } } } },
      "/api/projects/{id}/film": { get: { operationId: "getFilm", summary: "Assembled film manifest (segments, chapters, subtitles, verification summary).", parameters: [projectParam], responses: { "200": { description: "OK" } } } },
      "/api/projects/{id}/evaluate": { post: { operationId: "runEvaluation", summary: "Run the baseline-vs-CineMemory evaluation harness.", parameters: [projectParam], responses: { "202": { description: "Job started" } } } },
      "/api/projects/{id}/evaluations": { get: { operationId: "listEvaluations", summary: "Evaluation comparisons with metrics computed from records.", parameters: [projectParam], responses: { "200": { description: "OK" } } } },
    },
  };
}
