import { shortHash } from "../util/hash.js";
import { LLMOutputError, type LLMProvider, type StructuredRequest, type StructuredResult } from "./provider.js";

export interface FixtureLookup {
  task: string;
  fixtureKey: string;
  prompt: string;
  system: string;
}

/** Returns authored/recorded structured output for a request, or undefined when none exists. */
export type FixtureResolver = (lookup: FixtureLookup) => unknown | undefined;

export class FixtureMissingError extends Error {
  constructor(public readonly lookup: FixtureLookup) {
    super(
      `No development fixture for task "${lookup.task}" (key "${lookup.fixtureKey}"). ` +
        `Fixture mode only supports the bundled demo project. Set GEMINI_API_KEY to run real agents.`,
    );
    this.name = "FixtureMissingError";
  }
}

export const FIXTURE_NOTE = "DEVELOPMENT FIXTURE: authored/recorded response replayed offline. Not generated by a model.";

/**
 * Development-only provider that replays authored structured responses.
 * It never impersonates a model: provenance.provider is "fixture" and every artifact carries FIXTURE_NOTE.
 * Used for (a) deterministic tests of the agent pipeline and (b) running the bundled demo without credentials.
 */
export class FixtureLLMProvider implements LLMProvider {
  readonly name = "fixture";
  readonly model = "fixture";
  readonly supportsVision = false;
  private calls: FixtureLookup[] = [];

  constructor(private resolver: FixtureResolver) {}

  /** For tests: what was asked of the provider. */
  get history(): readonly FixtureLookup[] {
    return this.calls;
  }

  async generateStructured<T>(req: StructuredRequest<T>): Promise<StructuredResult<T>> {
    const lookup: FixtureLookup = {
      task: req.task,
      fixtureKey: req.fixtureKey ?? req.task,
      prompt: req.prompt,
      system: req.system,
    };
    this.calls.push(lookup);
    const raw = this.resolver(lookup);
    if (raw === undefined) throw new FixtureMissingError(lookup);
    const parsed = req.schema.safeParse(raw);
    if (!parsed.success) {
      throw new LLMOutputError(
        `Fixture for "${lookup.fixtureKey}" does not match schema: ${parsed.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; ")}`,
        JSON.stringify(raw),
      );
    }
    return {
      data: parsed.data,
      rawText: JSON.stringify(raw),
      provenance: {
        provider: this.name,
        model: this.model,
        task: req.task,
        createdAt: new Date().toISOString(),
        latencyMs: 0,
        promptHash: shortHash(req.system + "\n" + req.prompt),
        note: FIXTURE_NOTE,
      },
    };
  }
}
